baseURL = "https://dineshpai.in"
languageCode = "en-us"
title = "Dinesh Pai's blog"
paginate = 20

[params]
subtitle = "Field notes on investments and capital markets"
thumbnail = "thumb.png"

[taxonomies]
   tag = "tags"
   author = "authors"

[menu]
   [[menu.header]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

   [[menu.header]]
      identifier = "blog"
      name = "Blog"
      url = "/blog"
      weight = 2

   [[menu.header]]
      identifier = "podcast"
      name = "Podcasts"
      url = "/podcasts"
      weight = 2
